name: Build and Push Docker

on:
  push:
    branches:
      - "*"
  issue_comment:
  pull_request:
    types: [opened,closed]
    
permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: write

env:
  APP_NAME: "gcp-util"
jobs:

  deploy_pr:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy_this_pr')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.1.0

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/397995110920/locations/global/workloadIdentityPools/flik-workload-identity-pool-cicd/providers/flik-wip-provider-github-action'
        service_account: 'flik-external-sa-github-action@flik-infra.iam.gserviceaccount.com'

    - name: Setup GCP SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: flik-infra
    
    - name: Get branch names
      id: branch-name
      uses: tj-actions/branch-names@v7
      
    - uses: benjlevesque/short-sha@v2.2
      id: short-sha
      with:
        length: 5
        
    - uses: xt0rted/pull-request-comment-branch@v2
      id: comment-branch

    - name: Test
      run: | 
        echo ${{ github.event.pull_request.head }}
        echo ${{ github.head_ref }}
        echo ${{ github.event.pull_request.number }}
        echo ${{ github.event.number }}
        echo ${{ github.event.base_ref}}
        echo ${{ github.base_ref}}
        echo ${{ steps.comment-branch.outputs.head_ref }}
  
    - name: Login to GAR
      id: login-gar
      uses: docker/login-action@v3
      with:
        registry: asia-docker.pkg.dev/flik-infra
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Build Docker Image
      run: docker build -t asia-docker.pkg.dev/flik-infra/dev/${{ env.APP_NAME }}-${{ steps.comment-branch.outputs.head_ref }}:${{ github.sha }} .

    - name: Push Docker Images
      run: docker push asia-docker.pkg.dev/flik-infra/dev/${{ env.APP_NAME }}-${{ steps.comment-branch.outputs.head_ref }}:${{ github.sha }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: ${{ env.APP_NAME }}-${{ steps.comment-branch.outputs.head_ref }}
        image: 'asia-docker.pkg.dev/flik-infra/dev/${{ env.APP_NAME }}-${{ steps.comment-branch.outputs.head_ref }}:${{ github.sha }}'
        region: asia-southeast2
        project_id: flik-infra
        flags: |
          --allow-unauthenticated

    # - uses: actions/github-script@v3
    #   with:
    #     github-token: ${{secrets.GITHUB_TOKEN}}
    #     script: |
    #       github.issues.createComment({
    #         issue_number: context.issue.number,
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         body: '👋 ${{ steps.deploy.outputs.url }}'
    #       })

    - name: Add comment to PR
      uses: actions/github-script@v6
      if: always()
      with:
        script: |
          const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
          const success = '${{ job.status }}' === 'success';
          const body = `${success ? '${{ steps.deploy.outputs.url }} ✅' : 'failed ❌'}\n${url}`;

          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          })

  delete_pr:
    if: github.event.pull_request.merged == true || github.event.issue.pull_request && contains(github.event.comment.body, '/delete_deploy')
    runs-on: ubuntu-latest

    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 5

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/397995110920/locations/global/workloadIdentityPools/flik-workload-identity-pool-cicd/providers/flik-wip-provider-github-action'
          service_account: 'flik-external-sa-github-action@flik-infra.iam.gserviceaccount.com'

      - name: Setup GCP SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: flik-infra

      - name: Delete Cloud Run service
        run: |
          gcloud run services delete ${{ env.APP_NAME }}-${{ github.event.number }} --platform managed --region asia-southeast2 --project flik-infra --quiet
    
