name: Build and Push Docker

on:
  push:
    branches:
      - "*"
  issue_comment:
  pull_request:
    types: [opened,closed]
    
permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: write

env:
  APP_NAME: "gcp-util"
  GAR_URL: "asia-docker.pkg.dev"
  PROJECT_ID: "flik-dev"
  GAR_PROJECT_ID: "flik-infra"
  REGION: "asia-southeast2"
  VPC: "development-vpc-connector"
  INFRA_PROJECT_ID: "flik-infra"
  ENVIRONMENT: "dev"
  
jobs:

  deploy_pr:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy_this_pr')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.1.0

    - name: Checkout CI/CD Repository
      uses: actions/checkout@v4
      with: 
        repository: useflik/flik-cicd
        ref: main
        token: ${{secrets.GH_TOKEN}}
        path: ./.github/actions/cicd

    - name: GCP Preparation
      uses: ./.github/actions/cicd/action/prepare/gcp
      id: gcp_prep
      with:
        app_name: ${{ env.APP_NAME }}
        gar_registry_url: ${{ env.GAR_URL }}
        docker_user: ${{ secrets.DOCKER_USER }}
        docker_token: ${{ secrets.DOCKER_TOKEN }}

    - uses: xt0rted/pull-request-comment-branch@v2
      id: comment-branch

    - name: Build and Deploy service
      id: docker
      uses: ./.github/actions/cicd/action/pullrequest
      with:
        app_name: ${{ env.APP_NAME }}-${{ steps.comment-branch.outputs.head_ref }}
        environment: ${{ env.ENVIRONMENT }}
        gar_registry_url: ${{ env.GAR_URL }}
        gar_project_id: ${{ env.GAR_PROJECT_ID }}
        gcp_project_id: ${{ env.PROJECT_ID }}
        gcp_region: ${{ env.REGION }}
        gcp_vpc_connector: ${{ env.VPC }}
        gcp_vpc_egress: "all"
        port: "8080"
        cloudrun_env_vars: |
          env=${{ env.ENVIRONMENT }}
        gh_user: "cakhanif"
        gh_token: ${{secrets.GITHUB_TOKEN}}
        workdir: .


  delete_pr:
    if: github.event.pull_request.merged == true || github.event.issue.pull_request && contains(github.event.comment.body, '/delete_deploy')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CI/CD Repository
        if: 
        uses: actions/checkout@v4
        with: 
          repository: useflik/flik-cicd
          ref: main
          token: ${{secrets.GH_TOKEN}}
          path: ./.github/actions/cicd

      - name: GCP Preparation
        uses: ./.github/actions/cicd/action/prepare/gcp
        id: gcp_prep
        with:
          app_name: ${{ env.APP_NAME }}
          gar_registry_url: ${{ env.GAR_URL }}
          docker_user: ${{ secrets.DOCKERUSERNAME }}
          docker_token: ${{ secrets.DOCKERTOKEN }}      

      
      - uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - name: Delete Cloud Run service
        run: |
          gcloud run services delete ${{ env.APP_NAME }}-${{ steps.comment-branch.outputs.head_ref }} --platform managed --region ${{ env.REGION }} --project ${{ env.PROJECT_ID }} --quiet
    
