name: Build and Push Docker

on:
  push:
    branches:
      - "*"
  issue_comment:
  pull_request:
    
permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: write

jobs:
  deploy_dev:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy_dev')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.1.0

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/397995110920/locations/global/workloadIdentityPools/flik-workload-identity-pool-cicd/providers/flik-wip-provider-github-action'
        service_account: 'flik-external-sa-github-action@flik-infra.iam.gserviceaccount.com'

    - name: Setup GCP SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: flik-infra
  
    - name: Login to GAR
      id: login-gar
      uses: docker/login-action@v3
      with:
        registry: asia-docker.pkg.dev/flik-infra
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Get branch names
      id: branch-name
      uses: tj-actions/branch-names@v7
      
    - name: Build Docker Image
      run: docker build -t asia-docker.pkg.dev/flik-infra/dev/gcp-util:${{ github.sha }} .

    - name: Push Docker Images
      run: docker push asia-docker.pkg.dev/flik-infra/dev/gcp-util:${{ github.sha }}
    
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: gcp-util
        image: 'asia-docker.pkg.dev/flik-infra/dev/gcp-util:${{ github.sha }}'
        region: asia-southeast2
        project_id: flik-infra
        flags: |
          --allow-unauthenticated
  
  deploy_pr:
    if: contains(github.event.comment.body, '/deploy_this_pr')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.1.0

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/397995110920/locations/global/workloadIdentityPools/flik-workload-identity-pool-cicd/providers/flik-wip-provider-github-action'
        service_account: 'flik-external-sa-github-action@flik-infra.iam.gserviceaccount.com'

    - name: Setup GCP SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: flik-infra
    
    - name: Get branch names
      id: branch-name
      uses: tj-actions/branch-names@v7

    - name: Test
      run: echo ${{ github.event.pull_request.head }}
  
    - name: Login to GAR
      id: login-gar
      uses: docker/login-action@v3
      with:
        registry: asia-docker.pkg.dev/flik-infra
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Build Docker Image
      run: docker build -t asia-docker.pkg.dev/flik-infra/dev/${{ github.event.pull_request.head }}-gcp-util:${{ github.sha }} .

    - name: Push Docker Images
      run: docker push asia-docker.pkg.dev/flik-infra/dev/${{ steps.branch-name.outputs.head_ref_branch }}-gcp-util:${{ github.sha }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: ${{ steps.branch-name.outputs.head_ref_branch }}-gcp-util
        image: 'asia-docker.pkg.dev/flik-infra/dev/${{ steps.branch-name.outputs.head_ref_branch }}-gcp-util:${{ github.sha }}'
        region: asia-southeast2
        project_id: flik-infra
        flags: |
          --allow-unauthenticated

    - uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 ${{ steps.deploy.outputs.url }}'
          })