name: Build and Push Docker

on:
  push:
    branches:
     - "*"

jobs:
  build-and-push:
    if: github.event_name == 'push' || github.event_name == 'issue_comment' && contains(github.event.comment.body, 'deploy to staging')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.1.0

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERTOKEN }}

    - name: Build Docker Image
      run: docker build -t cakhanif/gcp-util:latest .

    - name: Push Docker Images
      run: docker push cakhanif/gcp-util:latest